version: '3'
services:
  Catalog-Module:
    image: saha94/catalog-service
    ports: 
     - "8005:80"
  redis:
    image: redis:alpine
  Review-Module:
    image: saha94/review-service
    ports:
     - "8055:90"
  Order-Module:
    image: saha94/order-service
    ports:
     - "8105:100"
  Main-Page:
    image: saha94/main-page
    build: .
    ports:
     - "8205:80"
